# Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    storage: nfs
provisioner: nfs.csi.k8s.io  ## Provisioner NFS CSI driver for Kubernetes
reclaimPolicy: Retain  ## Significa que o PV não será excluído quando o PVC for excluído.
volumeBindingMode: WaitForFirstConsumer
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.3.204/mnt/nfs
    volumeAttributes:
      server: 192.168.3.204
      share: /mnt/nfs
---
# Persisten tVolume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      storage: nfs      
---      
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.3"
            memory: 64Mi
        volumeMounts:
          - name: meu-pvc
            mountPath: /usr/share/nginx/html
      volumes:
        - name: meu-pvc
          persistentVolumeClaim:
            claimName: pvc-nfs